FROM nginx:1.19.3
#COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY nginx.conf /etc/nginx/conf.d/default.conf
#COPY build /usr/share/nginx/html/
#COPY docs /usr/share/nginx/html/api/docs/
#- ./nginx.conf:/etc/nginx/conf.d/default.conf
#- ../frontend/build:/usr/share/nginx/html/
#- ../docs/:/usr/share/nginx/html/api/docs/