# Generated by Django 4.2.4 on 2023-09-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taginrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_in', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='taginrecipe',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_in', to='recipes.tag'),
        ),
    ]
