# Generated by Django 4.2.4 on 2023-09-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_basket_unique_name_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='basket',
            name='unique_name_recipe',
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_name_basket_recipe'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_name_favorite_recipe'),
        ),
    ]
