# Generated by Django 4.2.4 on 2023-09-07 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя должно состоять из буквенно-цифровых символов, а также знаков ".", "@", "+", "-" и не содержать других символов.', regex='^[\\w.@+-]+$')], verbose_name='Уникальное имя пользователя'),
        ),
    ]
